# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
          Symfony\Component\Security\Core\User\User:
              algorithm: bcrypt
              cost: 12
          OrgaperoUserBundle\Entity\User:
              algorithm: bcrypt
    providers:
        in_memory:
            memory:
                users:
                    starlord:
                        password: $2y$12$a37ObU0sIFrkE4HC5wHqmO84uIBMywUWD64ON6dEyW5.5WZO.x48W
                        roles: 'ROLE_ADMIN'
        our_db_provider:
            entity:
                class: OrgaperoUserBundle:User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: orgapero_user_login
                check_path: orgapero_user_login

            logout:
                path:   /logout
                target: /

            pattern:    ^/
            http_basic: ~
            provider: our_db_provider

        secured_area:
            form_login:
                csrf_token_generator: security.csrf.token_manager