# src/AppBundle/Resources/config/validation.yml
AppBundle\Form\Model\ChangePassword:
    properties:
        oldPassword:
            - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
                message: 'Wrong value for your current password'