OrgaperoContributionsBundle\Entity\Contribution:
    type: entity
    table: null
    repositoryClass: OrgaperoContributionsBundle\Repository\ContributionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '48'
        quantity:
            type: integer
    manyToMany:
        activity:
            targetEntity: OrgaperoActivitiesBundle\Entity\Activity
            mappedBy: listContributions
    lifecycleCallbacks: {  }
