OrgaperoActivitiesBundle\Entity\Activity:
    type: entity
    table: null
    repositoryClass: OrgaperoActivitiesBundle\Repository\ActivityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToMany:
        party:
            targetEntity: Party
            inversedBy: listActivities
            joinTable:
                name: party_activity
                joinColumns:
                    party_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    activity_id:
                        referencedColumnName: id

        listContributions:
            targetEntity: OrgaperoContributionsBundle\Entity\Contribution
            inversedBy: activity
            joinTable:
                name: contribution_activity
                joinColumns:
                    contribution_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    activity_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
