OrgaperoActivitiesBundle\Entity\Activity:
    type: entity
    table: null
    repositoryClass: OrgaperoActivitiesBundle\Repository\ActivityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


    manyToMany:
        listContributions:
            targetEntity: OrgaperoContributionsBundle\Entity\Contribution
            inversedBy: activity
            joinTable:
                name: contribution_activity
                joinColumns:
                    contribution_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    activity_id:
                        referencedColumnName: id
    manyToOne:
        typeOfActivity:
            targetEntity: OrgaperoActivitiesBundle\Entity\TypeOfActivity
        party:
            targetEntity: Party
            inversedBy: listActivities

    lifecycleCallbacks: {  }
