OrgaperoActivitiesBundle\Entity\Activity:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        activity: Activity
        cinema: Cinema
    table: null
    repositoryClass: OrgaperoActivitiesBundle\Repository\ActivityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToMany:
        listContributions:
            targetEntity: OrgaperoContributionsBundle\Entity\Contribution
            inversedBy: activity
            joinTable:
                name: contribution_activity
                joinColumns:
                    contribution_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    activity_id:
                        referencedColumnName: id
    manyToOne:
        party:
            targetEntity: Party
            inversedBy: listActivities
    lifecycleCallbacks: {  }


