OrgaperoActivitiesBundle\Entity\TypeOfActivity:
    type: entity
    table: null
    repositoryClass: OrgaperoActivitiesBundle\Repository\TypeOfActivityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '96'

    manyToOne:
        parent:
            targetEntity: OrgaperoActivitiesBundle\Entity\TypeOfActivity
            inversedBy: children
    oneToMany:
        children:
            targetEntity: OrgaperoActivitiesBundle\Entity\TypeOfActivity
            mappedBy: parent


    lifecycleCallbacks: {  }
