<?php

namespace OrgaperoActivitiesBundle\Repository;

/**
 * TypeOfActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
