OrgaperoUserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: OrgaperoUserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 48
        name:
            type: string
            length: '48'
        firstname:
            type: string
            length: '48'
        email:
            type: string
            length: '96'
        password:
            type: string
            length: 255
        address:
            type: text
            nullable: true
        city:
            type: string
            length: '96'
            nullable: true
        country:
            type: string
            length: '96'
            nullable: true

    manyToMany:
        friendsWithMe:
            targetEntity: User
            mappedBy: friends

        friends:
            targetEntity: User
            inversedBy: friendsWithMe
            joinTable:
                name: friends
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    friend_user_id:
                        referencedColumnName: id

        invitations:
            targetEntity: OrgaperoActivitiesBundle\Entity\Party
            inversedBy: listParticipants
            joinTable:
                name: user_party
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    party_id:
                        referencedColumnName: id

    lifecycleCallbacks: {  }
